kitab/urls.py
from django.conf.urls import patterns, url
from django.conf import settings
from kitab import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^kitab/header/$', views.header, name='header'),
    url(r'^kitab/footer/$', views.footer, name='footer'),
    url(r'^kitab/sidebar/$', views.sidebar, name='sidebar'),
    url(r'^kitab/contact/$', views.contact, name='contact'),
    url(r'^kitab/aboutus/$', views.aboutus, name='aboutus'),
    url(r'^kitab/catagaries/$', views.catagaries, name='catagaries'),
    url(r'^kitab/catagaries/kitab/get_course/(?P<strm_id>\w+)/$', views.get_course, name = 'get_course'),
    url(r'^kitab/catagaries/kitab/get_subject/(?P<cours_id>\S+)/$', views.get_subject, name = 'get_subject'),
<<<<<<< HEAD
    url(r'^kitab/catagaries/kitab/show_book/(?P<sub_id>\S+)/$', views.show_book, name = 'show_book'),
=======
    url(r'^kitab/catagaries/kitab/show_book/(?P<sub_name>\w+)/$', views.show_book, name = 'show_book'),
>>>>>>> f2d8a1fdf3a7a72e7145a1d437698a997135cf9f
    url(r'^kitab/howitworks/$', views.howitworks, name='howitworks'),
    url(r'^kitab/requestbook/$', views.requestbook, name='requestbook'),
    url(r'^kitab/catagaries/(?P<pk>\d+)/$', views.show_book, name='show_book'),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
)

kitabghar/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'kitabghar.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^', include('kitab.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

kitab/models.py
from django.db import models
from django.core.validators import RegexValidator
import warnings
warnings.filterwarnings("ignore", "Field 'subbranch_title' doesn't have a default value")
# Create your models here.

class stream(models.Model):
	stream_name = models.CharField(max_length=50)
	stream_desc = models.TextField(max_length=2000)

	def __unicode__(self):              # __str__ on Python 3
        	return str(self.stream_name)

class course(models.Model):
	course_name = models.CharField(max_length=50)
	course_desc = models.TextField(max_length=2000)
	stream_id = models.ForeignKey(stream)

	def __unicode__(self):              
        	return str(self.course_name)        	
        	
class subject(models.Model):
    subject_name = models.CharField(max_length=200)
    course_id = models.ForeignKey(course, null = True)
    def __unicode__(self):              
        	return str(self.subject_name)		    	

class book(models.Model):
	book_name = models.CharField(max_length=200)
	book_author = models.CharField(max_length=200)
	book_isbn = models.IntegerField()
	book_edition = models.CharField(max_length=50)
	book_pdf_link = models.CharField(max_length=250)

	def __unicode__(self):              
        	return str(self.book_name)

class stream_course(models.Model):
	stream_id = models.ForeignKey(stream)
	course_id = models.ForeignKey(course)
	def __unicode__(self):
		return str(self.course_id)
		
class course_subject(models.Model):
	course_id = models.ForeignKey(course, null = True)
	subject_id = models.ForeignKey(subject)

	def __unicode__(self):              
        	return str(self.course_id)

class subject_book(models.Model):
	subject_id = models.ForeignKey(subject)
	book_id = models.ForeignKey(book)

	def __unicode__(self):              
        	return str(self.subject_id)

class bookrequest(models.Model):
	user_name = models.CharField(max_length=200)
	user_emailid = models.EmailField(max_length=254)
	book_name = models.CharField(max_length=200)
	book_author = models.CharField(max_length=200)
	book_edition = models.CharField(max_length=50)

	def __unicode__(self):
		return str(self.user_name)

class contactus(models.Model):
	fname = models.CharField(max_length=50)
	lname = models.CharField(max_length=50)
	email = models.EmailField(max_length=50)
	phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
	phone_no = models.CharField(validators=[phone_regex], max_length=15, blank=True)
	message = models.TextField(max_length=5000)

	def __unicode__(self):              
        	return str(self.fname) 		
		

kitab/views.py
from django.shortcuts import render, get_object_or_404, render_to_response
from django import forms
from django.http import HttpResponse, HttpResponseRedirect
from kitab.models import *
import json
# Create your views here.
def index(request):
	subject_list = subject.objects.all()
	book_list = book.objects.all()
	course_list = course.objects.all()
	context = {'subject_list':subject_list ,'book_list':book_list ,'course_list':course_list }
	return render(request, 'kitab/index.html',context)

def header(request):
	return render(request, 'kitab/header.html')

def footer(request):
	return render(request, 'kitab/footer.html')

def sidebar(request):
	stream_list = stream.objects.all()
	course_list = course.objects.all()
	subject_list = subject.objects.all()
	context = {'stream_list':stream_list, 'course_list':course_list, 'subject_list':subject_list }
	return render(request, 'kitab/sidebar.html', context)
'''
def contact(request):
	stream_list = stream.objects.all()
	subject_list = subject.objects.all()
	book_list = book.objects.all()
	course_list = course.objects.all()
	context = {'subject_list':subject_list ,'book_list':book_list ,'course_list':course_list ,'stream_list':stream_list}
	return render(request, 'kitab/contact.html',context)
'''
def contact(request):
	stream_list = stream.objects.all()
	subject_list = subject.objects.all()
	book_list = book.objects.all()
	course_list = course.objects.all()
	context = {'subject_list':subject_list ,'book_list':book_list ,'course_list':course_list ,'stream_list':stream_list}

	if request.method == 'GET':
		return render(request, 'kitab/contact.html',context)
	else:
		
		data = contactus(fname= request.POST['fname'], lname= request.POST['lname'], email = request.POST['email'], phone_no = request.POST['phone_no'], message = request.POST['message'])
		data.save()
		return HttpResponseRedirect('#')

def requestbook(request):
	stream_list = stream.objects.all()
	subject_list = subject.objects.all()
	book_list = book.objects.all()
	course_list = course.objects.all()
	context = {'subject_list':subject_list ,'book_list':book_list ,'course_list':course_list ,'stream_list':stream_list}

	if request.method == 'GET':
		return render(request, 'kitab/requestbook.html',context)
	else:
		''' -----fetching the data from the user and saving it in database---- '''
		data = bookrequest(user_name= request.POST['name'], user_emailid = request.POST['email'], book_name= request.POST['bname'], book_author= request.POST['authorname'], book_edition= request.POST['edn'])
		data.save()
		return HttpResponseRedirect('#')


def aboutus(request):
	stream_list = stream.objects.all()
	subject_list = subject.objects.all()
	book_list = book.objects.all()
	course_list = course.objects.all()
	context = {'subject_list':subject_list ,'book_list':book_list ,'course_list':course_list ,'stream_list':stream_list}
	return render(request, 'kitab/aboutus.html',context)

def catagaries(request):
	stream_list = stream.objects.all()
	subject_list = subject.objects.all()
	book_list = book.objects.all()
	course_list = course.objects.all()
	context = {'subject_list':subject_list ,'book_list':book_list ,'course_list':course_list ,'stream_list':stream_list}
	return render(request, 'kitab/catagaries.html',context)
'''
def show_project(request):
	branch_list = branch.objects.all()
	subbranch_list = subbranch.objects.all()
	context = {'branch_list':branch_list , 'subbranch_list':subbranch_list }
	return render(request, 'mutech/show_project.html/1/', context)
'''
def show_book(request, sub_name):
	current_subject = subject.objects.get(subject_name=sub_name)
	book_list = subject_book.objects.all().filter(subject_id_id=current_subject)
	
	'''
	book_dict = {}
	for b in book_list:
		book_dict[b.book_name] = b.book_name
	'''
	
	context = { 'book_list':book_list }
	return render(request, 'kitab/catagaries.html', context)

def show_book(request, sub_id):
	current_subject = subject.objects.get(stream_name=strm_id)
	book_list = subject_book.objects.all().filter(subject_id_id=current_subject)
	context = { 'book_list':book_list , 'books_list':books_list }
	return render(request, 'kitab/catagaries.html', context)

def howitworks(request):
	stream_list = stream.objects.all()
	subject_list = subject.objects.all()
	book_list = book.objects.all()
	course_list = course.objects.all()
	context = {'subject_list':subject_list ,'book_list':book_list ,'course_list':course_list ,'stream_list':stream_list}
	return render(request, 'kitab/howitworks.html',context)

def get_course(request, strm_id):
    current_stream = stream.objects.get(stream_name=strm_id)
    courses = course.objects.all().filter(stream_id_id=current_stream)

    course_dict = {}
    for c in courses:
        course_dict[c.course_name] = c.course_name

    #data = [course_dict]
    return HttpResponse(json.dumps(course_dict))


def get_subject(request, cours_id):
	current_course = course.objects.get(course_name=cours_id)
	subjects = subject.objects.all().filter(course_id_id=current_course)	
	
	subject_dict = {}
	for s in subjects:
		subject_dict[s.subject_name] = s.subject_name
	
	#data = [subject_dict]	
	return HttpResponse(json.dumps(subject_dict))

'''
def detail(request, stream_id1, course_id2=0, subject_id3=0):

	stream_list = stream.objects.all()
	course_list = course.objects.all()
	subject_list = subject.objects.all()
	book_list = book.objects.all()
	if stream_id1:
		streamId = get_object_or_404(stream, pk=stream_id1)
	context1 = {'course_list':course_list , 'subject_list':subject_list ,'stream_list':stream_list , 'streamId':streamId}

	return render(request, 'kitab/catagaries.html', context1)	
	'''

kitab/templates/kitab/aboutus.html
{% load staticfiles %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>KitabGhar/aboutus</title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<link href="{%static 'kitab/templatemo_style.css' %}" rel="stylesheet" type="text/css" />
<link href="{% static 'kitab/bootstrap.min.css' %}" rel="stylesheet" type="text/css"> 
<link href="{% static 'kitab/bootstrap.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'kitab/project_dropdown_menu2.css' %}" rel="stylesheet" type="text/css">
<!--<link href="{% static 'kitab/project_dropdown_menu1.css' %}" rel="stylesheet" type="text/css">-->
<link href="{% static 'kitab/agency.css' %}" rel="stylesheet" type="text/css">
</head>
<body>
<!--  Free CSS Templates from www.templatemo.com -->
<div id="templatemo_container">
    <div>{% include "kitab/header.html" %}</div>
    <div id="templatemo_content">
        
        <div>{% include "kitab/sidebar.html" %}</div>

        	<div class="" style="display:inline; margin-left:5%">
                <div class="col-md-" style="margin-top:2%;">
                    <img class="img-responsive" src="../../../media/{{q.aboutus_image}}" alt="Mutech image" style="height:300px; width:95%">
                </div>
                <div class="col-md-">
                    <h2>{{ q.aboutus_title }}</h2>
                    <p align="justify">Kitab-Ghar is a oline collection of links of the ebooks required for different course</p>
                    <p align="justify">Here at Kitab-Ghar we have collected the live link from which ebooks can be download with single click. we have classified books on the basis of subjects and courses </p>
                    <p align="justify">The Kitab-Ghar aims at provide the visitor a simple and sweet way to getting to the desired ebook</p>
                    <p align="justiy">And for our visitor we have also providing a mechanism for requesting the book in which the desirable ebook is searched by us and is provided to the user</p>
                    <p align="center"></p>
                </div>
           	</div>

        <div class="cleaner_with_height">&nbsp;</div>
    </div> <!-- end of content -->
    <div style="margin-left: -20px;">{% include "kitab/footer.html" %}</div>
    <!--  Free CSS Template www.templatemo.com -->
</div> <!-- end of container -->

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="{% static 'kitab/js/jquery.min.js' %}"></script>
<script src="{% static 'kitab/js/bootstrap.min.js' %}"></script>
<script src="{% static 'kitab/js/sb-admin-2.js' %}"></script>
<script src="{% static 'kitab/js/metisMenu.min.js' %}"></script>
</body>
</html>

kitab/templates/kitab/catagaries.html
{% load staticfiles %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>KitabGhar/Catagaries</title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<link href="{%static 'kitab/templatemo_style.css' %}" rel="stylesheet" type="text/css" />
<link href="{% static 'kitab/bootstrap.min.css' %}" rel="stylesheet" type="text/css"> 
<link href="{% static 'kitab/bootstrap.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'kitab/project_dropdown_menu2.css' %}" rel="stylesheet" type="text/css">
<!--<link href="{% static 'kitab/project_dropdown_menu1.css' %}" rel="stylesheet" type="text/css">-->
<link href="{% static 'kitab/agency.css' %}" rel="stylesheet" type="text/css">
</head>
<body>
<!--  Free CSS Templates from www.templatemo.com -->
<div id="templatemo_container">
    
    <div>{% include "kitab/header.html" %}</div>
    <div id="templatemo_content">
        
        <div>{% include "kitab/sidebar.html" %}</div>
         

                <div id="templatemo_content_right">     
                	{% if book_list %}
                    	{% for q in book_list %}         
	                      <div class="templatemo_product_box">
	                        <h1>{{ q.book_name }}  <span>(by {{ q.book_author }})</span></h1>
	                        <img src="{% static 'kitab/img/templatemo_image_01.jpg' %}" alt="image" />
	                        <div class="product_info">
	                          <p>Etiam luctus. Quisque facilisis suscipit elit. Curabitur...</p>
	                          <h3>$55</h3>
	                          <div class="buy_now_button"><a href="subpage.html">Buy Now</a></div>
	                          <div class="detail_button"><a href="">Download pdf</a></div>
	                        </div>
	                        <div class="cleaner">&nbsp;</div>
	                      </div>
	                      <div class="cleaner_with_width">&nbsp;</div>
<<<<<<< HEAD
=======
                          <div class="cleaner_with_height">&nbsp;</div>
>>>>>>> f2d8a1fdf3a7a72e7145a1d437698a997135cf9f
                    	{% endfor %}
                  {% else %}
                    <p>No Book Found</p>
                  {% endif %}
                  <!--
           
                	{% for q in streamId.book_set.all %}
                    <div class="templatemo_product_box">
                      <h1>{{ q.book_name }}  <span>(by {{ q.book_author }})</span></h1>
                      <img src="{% static 'kitab/img/templatemo_image_01.jpg' %}" alt="image" />
                      <div class="product_info">
                        <p>Etiam luctus. Quisque facilisis suscipit elit. Curabitur...</p>
                        <h3>$55</h3>
                        <div class="buy_now_button"><a href="subpage.html">Buy Now</a></div>
                        <div class="detail_button"><a href="">Download pdf</a></div>
                      </div>
                      <div class="cleaner">&nbsp;</div>
                    </div>
                    <div class="cleaner_with_width">&nbsp;</div>
                  {% endfor %}               
                -->
                </div><!-- end of content right -->
            
    </div> <!-- end of content -->
    
</div> <!-- end of container -->
<div style="margin-left: 0px;">{% include "kitab/footer.html" %}</div>
<!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>-->
<script src="{% static 'kitab/js/jquery.min.js' %}"></script>
<script>
     
    $(document).ready(function(){
        $('#id_stream').change(function(){
        	strm_id =$(this).val();
            //alert(strm_id);
            request_url = 'kitab/get_course/' + strm_id + '/';
            //alert(request_url)
            $.ajax({
                url: request_url,
                success: function(data){
                	data = $.parseJSON(data);
                	//alert(typeof(data))
                	$('#id_course').html('<option selected="' + "selected" + '">' + '' +'</option>');
                	$('#id_subject').html('<option selected="' + "selected" + '">' + '' +'</option>');
                	//alert(typeof(data));
	                $.each(data, function(key, value){
	                    //alert(typeof(data));
	                    //alert(JSON.stringify(data));
	                    $('#id_course').append('<option>' + value +'</option>');
	                }); 
            	}, 
	            errors: function(e) {
	                alert(e);
            	}
        	})
    	});

      	$('#id_course').change(function(){  
        	cours_id = $(this).val();
        	request_url = 'kitab/get_subject/' + cours_id + '/';
        	$.ajax({
                url: request_url,
                success: function(data){
	                data = $.parseJSON(data);
	                //alert(typeof(data))
	                //$('#id_subject').html('<option selected="' + "selected" + '">' + '' +'</option>');
	                $.each(data, function(key, value){
	                    //alert(typeof(data))
	                    //console.log(typeof(key), typeof(value));
	                    $('#id_subject').append('<option>' + value +'</option>');
	                }); 
            	}, 
	            errors: function(e) {
	                alert(e);
            	}
            })
        });

        $('#id_subject').change(function(){  
<<<<<<< HEAD
        sub_id = $(this).val();
        request_url = 'kitab/show_book/' + sub_id + '/';
=======
        sub_name = $(this).val();
        request_url = 'kitab/show_book/' + sub_name + '/';
>>>>>>> f2d8a1fdf3a7a72e7145a1d437698a997135cf9f
        alert(request_url)
        $.ajax({
                url: request_url,
                success: function(data){
                data = $.parseJSON(data);
<<<<<<< HEAD
=======
                alert(data);
>>>>>>> f2d8a1fdf3a7a72e7145a1d437698a997135cf9f
                //alert(typeof(data))
                //$('#id_subject').html('<option selected="' + "selected" + '">' + '' +'</option>');
                $.each(data, function(key, value){
                    //alert(typeof(data))
                    //console.log(typeof(key), typeof(value));
                    $('#id_subject').append('<option>' + value +'</option>');
                }); 
            }, 
            errors: function(e) {
                alert(e);
            }
              })
        });
     
}); 
    </script>  


</body>
</html>

kitab/templates/kitab/contact.html
{% load staticfiles %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>KitabGhar/ContactUs</title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<link href="{%static 'kitab/templatemo_style.css' %}" rel="stylesheet" type="text/css" />
<link href="{% static 'kitab/bootstrap.min.css' %}" rel="stylesheet" type="text/css"> 
<link href="{% static 'kitab/bootstrap.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'kitab/project_dropdown_menu2.css' %}" rel="stylesheet" type="text/css">
<!--<link href="{% static 'kitab/project_dropdown_menu1.css' %}" rel="stylesheet" type="text/css">-->
<link href="{% static 'kitab/agency.css' %}" rel="stylesheet" type="text/css">
<style>
    .header {
        background-color: ;
        color: #36A0FF;
        font-size: 27px;
        padding: 10px; 
    }
</style>
</head>
<body>
<script>
function fun() {
    alert("Your message is sent to admin!");
}
</script>
<div id="templatemo_container">
    <div>{% include "kitab/header.html" %}</div>
    <div id="templatemo_content">  
    <div class="">   
        <div>{% include "kitab/sidebar.html" %}</div>
        <div class="col-md-1"></div>
    
        <div class="col-md-6">
            
                <form class="form-horizontal" id="form" method="post" novalidation>
                {% csrf_token %}
                    <fieldset>
                        <legend class="text-center header">Contact us</legend>
                        <div class="form-group">
                            <div class="col-md-10 col-md-offset-1">
                                <input id="fname" name="fname" type="text" placeholder="First Name" class="form-control" onkeypress="return onlyChars(event)" required>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-10 col-md-offset-1">
                                <input id="lname" name="lname" type="text" placeholder="Last Name" class="form-control" onkeypress="return onlyChars(event)" required="required">
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-10 col-md-offset-1">
                                <input id="email" name="email" type="email" required data-validation-required-message="Please enter your email-id." placeholder="Email Address" class="form-control" required="required">
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-10 col-md-offset-1">
                                <input id="phone" name="phone_no" type="text" placeholder="Phone No" class="form-control" onkeypress="return onlyNumbers(event)" maxlength="12" minlength="10" required="required">
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-10 col-md-offset-1">
                                <textarea class="form-control" id="message" name="message" placeholder="Enter your message for us here. We will get back to you shortly." rows="7"
                                required="required"></textarea>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-12 text-center">
                                <button type="submit" class="btn btn-primary btn-lg" onclick="fun()" >Submit</button>
                      
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
		</div>            
    </div> <!-- end of content -->
    <div style="margin-left: -20px;">{% include "kitab/footer.html" %}</div>
    
</div> <!-- end of container -->


<script>
    function myFunction() {
        document.getElementById("demo").innerHTML = "Hello World";
    }
    function onlyChars(event)
    {
        var e =event;
        var charCode = e.which || e.keyCode;
        if ((charCode >= 65 && charCode <= 90) || (charCode >= 97 && charCode <= 122) || charCode == 8 || charCode == 9 || charCode == 32)
            return true;
        else 
            return false;
    }
    function onlyNumbers(event)             
    {
        var e =event; 
        var charCode = e.which || e.keyCode;
            if ((charCode >= 48 && charCode <= 57) || charCode == 8 || charCode == 37 || charCode == 39 || charCode == 9) 
                 return true;
            else
                 return false;
    }
</script>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="{% static 'kitab/js/jquery.min.js' %}"></script>
<script src="{% static 'kitab/js/bootstrap.min.js' %}"></script>
<script src="{% static 'kitab/js/sb-admin-2.js' %}"></script>
<script src="{% static 'kitab/js/metisMenu.min.js' %}"></script>
</body>
</html>

kitab/templates/kitab/footer.html
    {% load staticfiles %}
<div id="templatemo_footer">
    
    <a href="subpage.html">Home</a> | <a href="subpage.html">Search</a> | <a href="subpage.html">Books</a> | <a href="#">New Releases</a> | <a href="#">FAQs</a> | <a href="#">Contact Us</a>
    <br />
    Copyright © 2024 <a href="#"><strong>Your Company Name</strong></a> 
        <!-- Credit: www.templatemo.com --> 
</div> 
    <!-- end of footer -->
   

kitab/templates/kitab/header.html
{% load staticfiles %}
<div id="templatemo_menu">
        <ul>
            <li><a href="/">Home</a></li>
            <li><a href="/kitab/catagaries/">Category</a></li>
            <li><a href="/kitab/howitworks/">How it Works</a></li>            
            <li><a href="/kitab/aboutus/">About us</a></li>  
            <li><a href="/kitab/requestbook/">Request a Book</a></li> 
            <li><a href="/kitab/contact/">Contact</a></li>
        </ul>
    </div> <!-- end of menu -->
    
    <div id="templatemo_header">
        <div id="templatemo_special_offers">
            <p>
                <span>25%</span> discounts for
        purchase over $80
            </p>
            <a href="subpage.html" style="margin-left: 50px;">Read more...</a>
        </div>
        
        
        <div id="templatemo_new_books">
            <ul>
                <li>Suspen disse</li>
                <li>Maece nas metus</li>
                <li>In sed risus ac feli</li>
            </ul>
            <a href="subpage.html" style="margin-left: 50px;">Read more...</a>
        </div>
    </div> <!-- end of header -->

kitab/templates/kitab/howitworks.html
{% load staticfiles %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>KitabGhar/How it Works</title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<link href="{%static 'kitab/templatemo_style.css' %}" rel="stylesheet" type="text/css" />
<link href="{% static 'kitab/bootstrap.min.css' %}" rel="stylesheet" type="text/css"> 
<link href="{% static 'kitab/bootstrap.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'kitab/project_dropdown_menu2.css' %}" rel="stylesheet" type="text/css">
<!--<link href="{% static 'kitab/project_dropdown_menu1.css' %}" rel="stylesheet" type="text/css">-->
<link href="{% static 'kitab/agency.css' %}" rel="stylesheet" type="text/css">
</head>
<body>
<!--  Free CSS Templates from www.templatemo.com -->
<div id="templatemo_container">
    <div>{% include "kitab/header.html" %}</div>
    <div id="templatemo_content">
        
        <div>{% include "kitab/sidebar.html" %}</div>
        
            
        <div class="cleaner_with_height">&nbsp;</div>
    </div> <!-- end of content -->
    <div style="margin-left: -20px;">{% include "kitab/footer.html" %}</div>
    <!--  Free CSS Template www.templatemo.com -->
</div> <!-- end of container -->
<!-- templatemo 086 book store -->
<!-- 
Book Store Template 
http://www.templatemo.com/preview/templatemo_086_book_store 
-->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="{% static 'kitab/js/jquery.min.js' %}"></script>
<script src="{% static 'kitab/js/bootstrap.min.js' %}"></script>
<script src="{% static 'kitab/js/sb-admin-2.js' %}"></script>
<script src="{% static 'kitab/js/metisMenu.min.js' %}"></script>
</body>
</html>